
# Syntax highlighting
highlighter:         rouoge

# Permalinks
permalink:           /modern-blog-jekyll-sample/:title
relative_permalinks: false

# Setup
timezone:            your timezone # eg. Asia/Kathmandu
locale:              your locale language # eg. en_us
name:				         Renata Munhoz da Rocha
title:               Renata Munhoz da Rocha
tagline:             'tagline'
description:         'description'
url:                 site url
rss:                 rss feed url
baseurl:             '/modern-blog-jekyll-sample/'
baseurl_posts_img:   '/modern-blog-jekyll-sample/assets/images/posts/'
baseurl_featured_img: '/modern-blog-jekyll-sample/assets/images/hero/'
baseurl_featured_thumbnail: '/modern-blog-jekyll-sample/assets/images/thumbnail/'
baseurl_javascripts: '/modern-blog-jekyll-sample/assets/javascripts/'
icon:                /modern-blog-jekyll-sample/assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 Renata Munhoz da Rocha
  url:            	 https://diegopso.github.io/modern-blog-jekyll-sample/
  facebook:          username
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
